remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [K S Akhilkrishna]
logo: /IMG-20241017-WA0015.jpg
description: [Turning Data into insights]
